In [ ]:
print("Hello World!!")

In [ ]:
# 예외처리
# 실행 시 Error Class
# try ~ except : 에러가 날거 같은 구간을 알아야됨

try:
    num1 = int(input("첫 번째 정수 입력 >>"))
    num2 = int(input("두 번째 정수 입력 >>"))

    if num1 % num2 == 0:
        print(f"{num2}는 {num1}의 약수입니다.")
    else:
        print(f"{num2}는 {num1}의 약수가 아닙니다.")
except ValueError:
    print("정수를 입력해주세요.")
except ZeroDivisionError:
    print("0으로 나눌 수 없습니다.")
finally: # 예외 발생 상관 없이 실행되는 부분
    print("프로그램 종료")

In [ ]:
# temp.txt 를 읽었을 때 발생하는 에러 클래스 확인 후
# 해당 파일이 있다면 -> read()를 통해 모든 내용 출력
# 없다면 -> "해당 파일이 존재하지 않습니다." 출력!!
# 예외 발생 상관 없이 "프로그램 종료" 출력
try:
    with open("temp.txt", "r") as file:
        content = file.read()
        print(content)
except FileNotFoundError:
    print("해당 파일이 존재하지 않습니다.")
finally:
    print("프로그램 종료")

In [ ]:
# 추가 학습
# 사용자가 범위 내 인덱스를 입력하지 않았을 때
# 발생하는 에러 클래스를 확인하고
# 다음 문구를 출력 "존재하지 않는 인덱스입니다."
try:    
    my_list = [10, 20, 30, 40, 50]
    index = int(input("인덱스 번호를 입력 >>"))
    print(my_list[index])
except IndexError:
    print("존재하지 않는 인덱스입니다.")

In [ ]:
# 내장 라이브러리


# os(operating system)
import os
# 시스템 관련 라이브러리
# 파일 시스템, 디렉토리, 환경 변수, 경로 접근!!
# 현재 작업 경로 확인 : get current workind directory
print(os.getcwd())

# 폴더(디렉토리) 만들기 : make directory
try:
    os.mkdir("temp")
except FileExistsError:
    print("폴더가 이미 존재합니다.")

In [ ]:
# 폴더 삭제 : remove directory
# 비어 있는 폴더만 삭제 가능!!
try:
    os.rmdir("templates")
except OSError:
    print("디렉터리가 비어있지 않습니다.")

In [ ]:
# listdir()
# 특정 경로 내 폴더 및 파일 변환
print(os.listdir())
print(os.listdir("templates"))
print(os.listdir("../")) # 상위 폴더

# 현재 경로에 있는
# day로 시작하는 파일 개수는?
count = 0
for f in os.listdir():
    if f.startswith("day"):
        count += 1
print(count)

In [ ]:
# 파일 및 폴더 이름 변경
# os.mkdir("temp") 로 폴더 만들고 진행
os.rename("temp", "temp2")
# os.rename("test.txt", "test2.txt") 도 가능

In [ ]:
os.path.exists("test.txt")

In [ ]:
# 사용자로부터 생성할 폴더 이름 입력 받고
# 해당 폴더가 존재하면
# "이미 존재합니다."

folder_name = input("생성할 폴더 이름 >>")
if not os.path.exitst(folder_name):
    os.mkdir(folder_name)
else:
    print(f"{folder_name}가 이미 존재합니다.")

In [ ]:
# 특정 폴더 내 test.txt를 만들어보자
folder_path = "abc"
file_name = "text.txt"
# new_file_path = f"{folder_path}/{file_name}"
# os.path.join() 운영체제의 경로 결합 규칙에 따라 경로 결합
new_file_path = os.path.join(folder_path, file_name)

with open(new_file_path, "w") as file:
    file.write("Hello World!!")

In [ ]:
# 폴더 및 파일의 이동, 복사, 삭제 등
# 좀 더 강력한 파일 관리 기능 지원!!
import shutil

shutil.copy("number.txt", "copy.txt") # 파일 복사
shutil.copytree("templates", "copy") # 폴더 전체 복사

In [ ]:
# 파일 및 폴더 이동
shutil.move("copy.txt", "copy/copy.txt")

In [ ]:
# 파일 및 폴더 삭제
# 파일 삭제는
# os.remove("test2.txt")
# 폴더 삭제 - 한번 더 고민하고 실행하기!
shutil.rmtree("copy")

In [ ]:
# 1) number.txt 를 copy.txt로 복사
# 2) 빈 폴더 test 생성!
# 3) copy.txt를 test 폴더로 이동
# 4) test 폴더 이름 test2로 변경
# 5) test2 폴더 내용까지 삭제

shutil.copy("number.txt", "copy.txt")
os.mkdir("test")
shutil.move("copy.txt", "test/copy.test")
os.rename("test", "test2")
shutil.rmtree("test2")

In [ ]:
# 파일 검색 시
# 특정 패턴(와일드 패턴)을 사용하여 검색
import glob

In [ ]:
# 현재 경로의 모든 파일 탐색
all_files = glob.glob("*")
print(all_files)

# 현재 경로의 .ipynb 파일 탐색
print(glob.glob("*.ipynb"))

# 5글자짜리 .ipynb 파일 탐색
print(glob.glob("?????.ipynb"))

# t로 시작하는 파일 & 폴더 탐색
print(glob.glob("t*"))

# c or d 로 시작하는 파일 탐색
print(glob.glob("[cd]*.*"))

In [ ]:
# 하위 폴더까지 탐색
# 재귀 옵션 True로 진행!! - 기본은 false
print(glob.glob("**/*", recursive=True))

In [ ]:
os.chdir("Users/kccistc/Desktop/workspace/")
os.getcwd()
# os.chdir("../../../../")
# os.chdir("C:\\")
# os.getcwd()
# print(glob.glob("C:\**/*.py", recursive=True))
print(glob.glob("C:\**/*.py", recursive=True))

In [ ]:
# csv
import csv

In [ ]:
# csv 파일 쓰기
with open("contact.csv", "w", newline="") as file:
    # csv 형태로 쓰기 위한 Writer 객체 생성
    header = ["name", "age", "mbti"]
    writer = csv.DictWriter(file, fieldnames=header)

    writer.writeheader()

    writer.writerow({"name":"나예호", "age":20, "mbti":"ENFJ"})
    writer.writerow({"name":"수지", "age":30, "mbti":"INFP"})

In [ ]:
with open("contact.csv", "r") as file:
    # reader = csv.reader(file)
    reader = csv.DictReader(file)
    for row in reader:
        print(row["age"])

In [ ]:
# 실제 데이터를 가지고 csv 연습
# 다운로드에 있던 방금 받은 csv를 workspace로 옮기고 싶다
shutil.move("../../Downloads/병무청_현역병(징집병_모집병) 입영현황_20241231.csv", "army.csv")

In [ ]:
# 현역(징집)병 입영인원 총 합(명)
with open("army.csv", "r", encoding="euc-kr") as f:
    count = 0
    reader = csv.DictReader(f)
    for row in reader:
        count += int(row["현역(징집)병 입영인원"])
    print(f"현역(징집)병 입영인원: 총 {count}명")

In [ ]:
# 근로소득 자료를 토대로 다음의 2개 항목을 출력하시오
# 1) 중앙값 (50% 구간의 근로소득)
# 2) 평균값 (구간별 인원수, 구간별 소득금액)
shutil.move("../../Downloads/국세청_근로소득 백분위(천분위) 자료_20241231.csv", "salaray.csv")

In [ ]:
with open("salary.csv", "r", encoding="euc-kr") as f:
    reader = csv.DictReader(f)
    for row in reader:
        if "10%" in row["구분"] :
            earned_income = int(row["근로소득금액"]) / int(row["인원"])
            print(f"10% 구간 근로소득 : {earned_income:.2f}억 원")

In [ ]:
with open("salary.csv", "r", encoding="euc-kr") as f:
    reader = csv.DictReader(f)
    total_popular = 0
    total_salary = 0
    for row in reader:
        total_popular += int(row["인원"])
        total_salary += int(row["근로소득금액"])
print(f"평균 근로소득 : {total_salary / total_popular * 10000 : .2f}만원")

In [ ]:
with open("salary.csv", "r", encoding="euc-kr") as f:
    reader = csv.DictReader(f)
    people = 0
    salary = 0
    count = 0
    search = "40%"
    for row in reader:
        people += int(row["인원"])
        salary += int(row["근로소득금액"])
        count += 1
        if search in row["구분"]:
            earned_income = int(row["근로소득금액"]) / int(row["인원"]) * 10000
            final_tax = int(row["결정세액"]) / int(row["인원"]) * 10000
            print(f"상위 {search} 구간의 근로소득금액: {earned_income:.2f}만원")
            print(f"상위 {search} 구간의 결졍세액: {final_tax:.2f}만원")

    print(f"평균 근로소득 : {salary / people * 10000 : .2f}만원")

In [ ]:
# JSON 파일을 다뤄보자
# 웹 상의 csv 혹은 json 등을 가져와보자
# !하면 터미널에다가 입력하는 것과 동일한 효과 (-o pokemon.json)
!curl -L https://github.com/intelcoder/PokemonGO-Pokedex-Korean/raw/refs/heads/master/pokedex-korean.json -o pokemon.json

In [ ]:
import json
with open("pokemon.json", "r") as f:
    data = json.load(f)
    print(data[0])

In [ ]:
# type에 "풀"이 들어간 포켓몬의 평균 키
with open("pokemon.json", "r") as f:
    data = json.load(f)
    grass_height = 0
    grass_count = 0
    for pokemon in data:
        if "풀" in pokemon["type"]:
            grass_height += float(pokemon["height"].strip("m"))
            grass_count += 1
    
    print(f"{grass_height / grass_count : .2f}m")

In [4]:
# json 쓰기
data2 = {"이름":"나예호", "나이":20, "mbti":"ENFJ"}
data3 = {"이름":"수지", "나이":30, "mbti":"INFP"}

with open("contact2.json", "w", encoding="euc-kr") as f:
    json.dump([data2, data3], f)
    
with open("contact2.json", "r", encoding="euc-kr") as f:
    data = json.load(f)
    print(data)

[{'이름': '나예호', '나이': 20, 'mbti': 'ENFJ'}, {'이름': '수지', '나이': 30, 'mbti': 'INFP'}]

In [8]:
import os
os.getcwd()

'c:\\Users\\kccistc\\Desktop\\workspace'

In [2]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas in c:\users\kccistc\appdata\roaming\python\python310\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\kccistc\appdata\roaming\python\python310\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\envs\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kccistc\appdata\roaming\python\python310\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\envs\myenv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [3]:
# DataFrame : 2차원
# Series : 1차원
s1 = pd.Series([10, 20, 30, 40, 50])
# print(s1)

names = ["나예호", "수지", "아이유"]
ages = [20, 30, 31]
mbti = ["ENFJ", "INFP", "INTP"]

data = {"name" : names, "age": ages, "mbti": mbti}
df = pd.DataFrame(data)
df

  name  age  mbti
0  나예호   20  ENFJ
1   수지   30  INFP
2  아이유   31  INTP

In [9]:
df_pokemon = pd.read_json("pokemon.json")
df_pokemon.head() # 상위 5개 데이터 추출
df_pokemon.tail() # 하위 5개 데이터 추출
df_pokemon.head(3) # 상위 3개 데이터 추출
df_pokemon.sample(3) # 랜덤 3개 데이터 추출(없으면 1)

# 행렬(matrix)
df_pokemon.info() # 해당 DataFrame의 정보

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              151 non-null    int64
 1   num             151 non-null    int64
 2   name            151 non-null    object
 3   img             151 non-null    object
 4   type            151 non-null    object
 5   height          151 non-null    object
 6   weight          151 non-null    object
 7   candy           151 non-null    object
 8   egg             73 non-null     object
 9   multipliers     70 non-null     object
 10  weaknesses      151 non-null    object
 11  next_evolution  70 non-null     object
 12  prev_evolution  71 non-null     object
dtypes: int64(2), object(11)
memory usage: 15.5+ KB

In [2]:
!curl -L https://github.com/lgreski/pokemonData/raw/refs/heads/master/Pokemon.csv -o pokemon.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 74060  100 74060    0     0   505k      0 --:--:-- --:--:-- --:--:--  505k

In [11]:
df_poke = pd.read_csv("pokemon.csv")
# df_poke.info()
df_poke.describe() # 수치데이터를 확인
df_poke.head()
# DataFrame 기본 인덱싱 및 슬라이싱
# 인덱싱
# 데이터프레임[컬럼명] -> 1차원 시리즈
df_poke["Name"]
# 데이터프레임[["컬럼명1", "컬렁명2"]] -> 2차원 데이터 프레임
df_poke[["Name", "Total"]]

            Name  Total
0      Bulbasaur    318
1        Ivysaur    405
2       Venusaur    525
3     Charmander    309
4     Charmeleon    405
...          ...    ...
1210  Iron Crown    590
1211   Terapagos    450
1212   Terapagos    600
1213   Terapagos    700
1214   Pecharunt    600

[1215 rows x 2 columns]

In [4]:
# 조건에 맞는 데이터 추출
# loc (location)
# 데이터프레임.loc[행 인덱싱 값, 열 인덱싱 값]
df_poke.loc[0] # 0번 인덱스의 data -> 1차원 시리즈
df_poke.loc[0, "Total"] # 0번 인덱스의 Total 컬럼 data
df_poke.loc[0, "Name"] # 0번 인덱스의 Name 컬럼 data

# 데이터프레임.loc[행 슬라이싱]
df_poke.loc[0 : 2] # 0번 인덱스 ~ 2번 인덱스

# 데이터프레임.loc[행 슬라이싱, 열 슬라이싱]
df_poke.loc[0 : 2, "Name":"Total"] # 0 ~ 2번 인덱스, Name ~ Total 컬럼

        Name Form  Type1   Type2  Total
0  Bulbasaur       Grass  Poison    318
1    Ivysaur       Grass  Poison    405
2   Venusaur       Grass  Poison    525

In [8]:
# Boolean Indexing
# 포켓몬 Total 이 400이상인 데이터들만 확인!!
df_poke["Total"] >= 400

# 데이터프레임[행 인덱싱] <- 여기에 series를 넣을꺼임
df_poke[df_poke["Total"] >= 400]

# 만약 그 조건을 만족하는 1세대 포켓몬만 [조건이 & 하나만]
df_poke.loc[(df_poke["Total"] >= 400) & (df_poke["Generation"] == 1)]

,ID,Name,Form,Type1,Type2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
1,2,Ivysaur,,Grass,Poison,405,60,62,63,80,80,60,1
2,3,Venusaur,,Grass,Poison,525,80,82,83,100,100,80,1
4,5,Charmeleon,,Fire,,405,58,64,58,80,65,80,1
5,6,Charizard,,Fire,Flying,534,78,84,78,109,85,100,1
7,8,Wartortle,,Water,,405,59,63,80,65,80,58,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,Moltres,,Fire,Flying,580,90,100,90,125,85,90,1
147,148,Dragonair,,Dragon,,420,61,84,65,70,70,70,1
148,149,Dragonite,,Dragon,Flying,600,91,134,95,100,100,80,1
149,150,Mewtwo,,Psychic,,680,106,110,90,154,90,130,1
150,151,Mew,,Psychic,,600,100,100,100,100,100,100,1

In [ ]:
# Type1이 Fire인 포켓몬의 개수 = 76
df_poke.loc[df_poke["Type1"] == "Fire"]
# Type1이 Water인 포켓몬 중 Total 500이상인 포켓몬의 개수 = 47
# 개수는 출력 시 나오는 rows를 확인하자!!
df_poke.loc[(df_poke["Type1"] == "Water") & (df_poke["Total"] >= 500)].count()

ID            47
Name          47
Form          47
Type1         47
Type2         47
Total         47
HP            47
Attack        47
Defense       47
Sp. Atk       47
Sp. Def       47
Speed         47
Generation    47
dtype: int64

In [ ]:
# 데이터프레임 인덱싱 및 슬라이싱
# loc는 정확히 일치했을때, iloc는 앞에서부터 차례대로
# iloc (Integer Location) **가장 많이 씀
# 데이터프레임.iloc[행 인덱스 정수]
df_poke.iloc[0]
# 데이터프레임.iloc[행 인덱스 정수, 열 인덱스 정수]
df_poke.iloc[0, 1]

# 데이터프레임.iloc[행 인덱스 정수 슬라이싱]
# iloc -> 마지막 범위 포함 X
df_poke.iloc[0 : 3]

# 데이터프레임.iloc[행 인덱스 정수 슬라이싱, 열 인덱스 정수 슬라이싱]
df_poke.iloc[0 : 3, 1 : 6]

        Name Form  Type1   Type2  Total
0  Bulbasaur       Grass  Poison    318
1    Ivysaur       Grass  Poison    405
2   Venusaur       Grass  Poison    525

In [24]:
# 모든 포켓몬의 이름을 출력
df_poke.loc[ : , "Name"]
df_poke["Name"]

df_poke.iloc[ : , 1]
# df_poke[1] # 이건 안됨

# iloc -> Boolean Indexing이 안된다...
# df_poke.iloc[df_poke["Total"] >= 400]

0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
           ...
1210    Iron Crown
1211     Terapagos
1212     Terapagos
1213     Terapagos
1214     Pecharunt
Name: Name, Length: 1215, dtype: object

In [ ]:
# 포켓몬 Total로 통계적 활동
# Total Column에 대한 통계 수치 확인
df_poke["Total"].describe()

# Total Column의 mean(평균값)
df_poke["Total"].mean()
# max(최댓값), min(최솟값), median(중앙값) 등등 가능

np.float64(443.1045267489712)

In [ ]:
# 타입별 Total 평균값
# 세대별 HP의 중앙값

# 그룹화!!
# 타입별로 먼저 그룹화
df_poke.groupby("Type1")["Total"].mean()
df_poke.groupby("Generation")["HP"].median()

Generation
1    60.0
2    67.5
3    61.0
4    70.0
5    70.0
6    71.0
7    68.0
8    70.0
9    80.0
Name: HP, dtype: float64

In [33]:
# 타입별 Total의 최댓값과 최솟값
# agg로 합쳐서 사용 가능
df_poke.groupby("Type1")["Total"].agg(["max", "min"])

           max  min
Type1
Bug        600  180
Dark       680  220
Dragon     780  270
Electric   670  205
Fairy      700  218
Fighting   700  210
Fire       680  250
Flying     580  245
Ghost      680  275
Grass      630  180
Ground     770  265
Ice        580  185
Normal     720  190
Poison    1125  210
Psychic    780  198
Rock       700  240
Steel      700  290
Water      770  175

In [ ]:
# 특정 컬럼만 추출하여 복사

# 복사에 대해 알아보자
# 얕은 복사
list_snack = ["뿌뿌딸기맛", "뿌뿌메론맛", "뿌뿌초코맛"]
print(list_snack[0])

list_copy = list_snack
print(list_copy)
print(list_copy[0])

list_copy[0] = "뿌뿌바나나맛"
print(list_copy)
print(list_snack)

# 리스트가 1차원이면 리스트명.copy()
list_copy2 = list_snack.copy() # 조금 덜 얕은
print(list_copy2)
list_copy2[0] = "맛동산"
print(list_copy2)
print(list_snack)

뿌뿌딸기맛
['뿌뿌딸기맛', '뿌뿌메론맛', '뿌뿌초코맛']
뿌뿌딸기맛
['뿌뿌바나나맛', '뿌뿌메론맛', '뿌뿌초코맛']
['뿌뿌바나나맛', '뿌뿌메론맛', '뿌뿌초코맛']
['뿌뿌바나나맛', '뿌뿌메론맛', '뿌뿌초코맛']
['맛동산', '뿌뿌메론맛', '뿌뿌초코맛']
['뿌뿌바나나맛', '뿌뿌메론맛', '뿌뿌초코맛']

In [ ]:
list_drink = ["ZICO", "솔의눈", [0, 1, 2]]
print(list_drink)

list_copy3 = list_drink.copy()
print(list_copy3)
list_copy3[0] = "데자와"
print(list_copy3)
print(list_drink)

list_copy3[2][0] = 100
print(list_copy3)
print(list_drink)
# 1차원이 아닐 때 쓰면 꼬여버림

['ZICO', '솔의눈', [0, 1, 2]]
['ZICO', '솔의눈', [0, 1, 2]]
['데자와', '솔의눈', [0, 1, 2]]
['ZICO', '솔의눈', [0, 1, 2]]
['데자와', '솔의눈', [100, 1, 2]]
['ZICO', '솔의눈', [100, 1, 2]]

In [ ]:
# 깊은 복사!! - 메모리적으론 손해
from copy import deepcopy
list_copy4 = deepcopy(list_drink)
print(list_copy4)

list_copy4[2][0] = 200
print(list_copy4)
print(list_drink)

['ZICO', '솔의눈', [100, 1, 2]]
['ZICO', '솔의눈', [200, 1, 2]]
['ZICO', '솔의눈', [100, 1, 2]]

In [ ]:
# 얕은 복사 : 복사본이 원본을 바라본다.
# 깊은 복사 : 복사본이 원본을 바라보지 않는다.
df_copy5 = df_poke # 얕은 복사
df_copy6 = df_poke.copy() # 깊은 복사

In [ ]:
import pandas as pd
df_poke = pd.read_csv("pokemon.csv")